### ISSUE TITLE
[ubuntu][windows][org.telegram.api.engine.TimeoutException] doRpcCallNonAuth 

### ISSUE THREAD

**Issue by k4mr4n** [telegram-s/telegram-bot#11]
in windows and also in ubuntu (vm) after i write server name i'm get timeout exception in process of "Loading fresh DC list.."
am i miss something?!

Loading fresh DC list...Exception in thread "main" org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:364)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
    at org.telegram.bot.Application.login(Application.java:380)
    at org.telegram.bot.Application.main(Application.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by LukeLR** [comment]
The Datacenter IPs are outdated. I just started using this project for learning purposes, and I quickly figured that out. Just needed to follow the stack trace ;) I forked the repo, updated the IPs and submitted a pull request (#12) ;) But until this is done, you can use my fork of the repo https://github.com/LukeLR/telegram-bot which is exactly the same code with the updated IPs ;) This should fix your issue
