### ISSUE TITLE
Cannot retrieve DC list (Unknown dispatcherId 'connection')

### ISSUE THREAD

**Issue by susemeee** [telegram-s/telegram-bot#6]
Execution program log:

Exception in thread "Connection#757108857" java.lang.RuntimeException: Unknown dispatcherId 'connection'
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:102)
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:63)
    at org.telegram.mtproto.transport.TransportTcpPool.<init>(TransportTcpPool.java:62)
    at org.telegram.mtproto.MTProto.<init>(MTProto.java:116)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:895)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:946)
Exception in thread "main" org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
    at org.telegram.bot.Application.login(Application.java:380)
    at org.telegram.bot.Application.main(Application.java:40)

**Comment by pouraghajanOldAcc** [comment]
Same issue here, too.
I have used the new IPs as well, but it didn't help.
It would be appreciated if someone can leave a comment on this. I'm stuck for 2 days now!!

Exception in thread "Connection#1957038341" java.lang.RuntimeException: Unknown dispatcherId 'connection'
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:102)
    at com.droidkit.actors.ActorSystem.actorOf(ActorSystem.java:63)
    at org.telegram.mtproto.transport.TransportTcpPool.<init>(TransportTcpPool.java:62)
    at org.telegram.mtproto.MTProto.<init>(MTProto.java:116)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.waitForDc(TelegramApi.java:895)
    at org.telegram.api.engine.TelegramApi$ConnectionThread.run(TelegramApi.java:946)
Exception in thread "main" org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:364)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
    at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
    at org.telegram.bot.Application.login(Application.java:380)
    at org.telegram.bot.Application.main(Application.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by pouraghajanOldAcc** [comment]
My problem just solved using older version of telegram api and type language jars (telegram-api-1.0-SNAPSHOT.jar and tl-api-v11.jar)
Hope to see better support from project owner and more participation by others in future ;)
