### ISSUE TITLE
MTProto#1002:Auth key invalidated

### ISSUE THREAD

**Issue by amol-ds** [telegram-s/telegram-bot#7]
I am trying to run this project but I am getting IOException. I have following log details in my console. Is this because of AppInfo parameters like app_id & app_hash? I have tested app_id & app_hash with Telegram Android client, and its working fine.

Use test DC? (write test for test servers): production
Using production servers
TelegramApi#1001:Phase 0 in 2 ms
TelegramApi#1001:Phase 1 in 123 ms
TelegramApi#1001:Timeout Iteration
TelegramApi#1001:Phase 2 in 6 ms
TelegramApi#1001:Sender iteration
TelegramApi#1001:Connection iteration
api#1001#Downloader:DownloadFileThread iteration
api#1001#Downloader:DownloadFileThread iteration
TelegramApi#1001:#1: waitForDc
TelegramApi#1001:#1: Creating proto for dc
TelegramApi#1001:#1: Creating key
api#1001#Downloader:DownloadFileThread iteration
TelegramApi#1001:Phase 3 in 7 ms
Loading fresh DC list...TelegramApi#1001:>> #0: help.getConfig#c4f9186b
TelegramApi#1001:Timeout Iteration
api#1001#Uploader:UploadFileThread iteration
api#1001#Uploader:UploadFileThread iteration
api#1001#Uploader:UploadFileThread iteration
api#1001#Downloader:DownloadFileThread iteration
TelegramApi#1001:Sender iteration
api#1001#Uploader:UploadFileThread iteration
TransportRate:Transport: #1 173.240.5.1:443 #1.0
TransportRate:tryConnection #1
TransportRate:onConnectionSuccess #1
TransportRate:Transport: #1 173.240.5.1:443 #1.0
Authorizer:Solved PQ in 109 ms
TransportRate:Transport: #1 173.240.5.1:443 #1.0
TransportRate:Transport: #1 173.240.5.1:443 #1.0
ActorDispatcher:Dispatching action: check for connector
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: check for connector
TransportTcpPool#1002:Creating context...
ActorDispatcher:Dispatching action: schedule for scheduller
TransportRate:tryConnection #1
ActorDispatcher:Dispatching action: pingDelay for internal_actions
ActorDispatcher:Dispatching action: pingDelay for internal_actions
TransportRate:Transport: #1 173.240.5.1:443 #1.0
ActorDispatcher:Dispatching action: requestSalts for internal_actions
MTProto#1001:Salt check timeout
MTProto#1002:Ping delay disconnect for 75 sec
MTProto#1001:Too few actual salts: 0, requesting news
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: check for connector
ActorDispatcher:Dispatching action: requestSalts for internal_actions
MTProto#1002:Salt check timeout
MTProto#1002:Too few actual salts: 0, requesting news
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: pingDelay for internal_actions
ActorDispatcher:Dispatching action: check for connector
MTProto#1002:sendMessage #5 account.registerDevice#446c712c
ActorDispatcher:Dispatching action: requestSalts for internal_actions
TransportTcpPool#1003:Creating context...
ActorDispatcher:Dispatching action: requestSalts for internal_actions
TransportRate:tryConnection #1
ActorDispatcher:Dispatching action: requestSalts for internal_actions
MTProto#1003:Salt check timeout
MTProto#1003:Too few actual salts: 0, requesting news
TelegramApi#1001:#MTProto #1002 created in 2222 ms
TelegramApi#1001:Connection iteration
TelegramApi#1001:Sender iteration
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: requestSalts for internal_actions
TransportTcpPool#1002:Context created.
TransportTcpPool#1003:Context created.
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: check for connector
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: check for connector
MTProto#1002#Scheduller:Forgetting message: #3
MTProto#1003#Scheduller:Forgetting message: #4
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 12
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 20
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 32
MTProto#1003#Scheduller:Iteration: count: 3, confirm:0
MTProto#1003#Scheduller:Building package
Scheduller:Prepare package: account.registerDevice#446c712c of size 84
Scheduller:Total size: 84
Scheduller:Prepare package: ping_delay_disconnect#f3427b8c of size 16
Scheduller:Total size: 100
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 108
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 120
MTProto#1002#Scheduller:Iteration: count: 4, confirm:0
MTProto#1002#Scheduller:Building package
MTProto#1002#Scheduller:Adding msg_ack: 0
MTProto#1003#Scheduller:Adding msg_ack: 0
MTProto#1002#Scheduller:Adding package: #5 account.registerDevice#446c712c (6107397397028012036, 1)
MTProto#1003#Scheduller:Adding package: #9 ping#7abe77ec (6107397397028012036, 1)
MTProto#1002#Scheduller:Adding package: #6 ping_delay_disconnect#f3427b8c (6107397397028012040, 3)
MTProto#1003#Scheduller:Adding package: #10 get_future_salts#b921bd04 (6107397397028012044, 3)
MTProto#1002#Scheduller:Adding package: #8 get_future_salts#b921bd04 (6107397397028012048, 5)
MTProto#1002#Scheduller:Adding package: #11 ping#7abe77ec (6107397397028012056, 7)
MTProto#1002#Scheduller:Sending Package (6107397397028012060, 8)
MTProto#1003#Scheduller:Adding package: #12 ping#7abe77ec (6107397397028012052, 5)
MTProto#1003#Scheduller:Sending Package (6107397397028012064, 6)
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
MTProto#1003#Transport3:Start reading message: pre
MTProto#1003#Transport3:Start reading message: 88
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002#Transport2:Start reading message: 88
TransportTcpPool#1002:onSuccess
TransportTcpPool#1003:onSuccess
TransportTcpPool#1003:reset
TransportTcpPool#1002:reset
TransportRate:onConnectionSuccess #1
TransportRate:onConnectionSuccess #1
TransportRate:Transport: #1 173.240.5.1:443 #1.0
TransportRate:Transport: #1 173.240.5.1:443 #1.0
ActorDispatcher:Dispatching action: new for response
ActorDispatcher:Dispatching action: new for response
MTProto#1003:MTProtoMessage: bad_server_salt#edab447b
MTProto#1002:MTProtoMessage: bad_server_salt#edab447b
MTProto#1002:BadMessage: 48 #6107397397028012060
MTProto#1003:BadMessage: 48 #6107397397028012064
MTProto#1002:Reschedule messages because bad_server_salt #6107397397028012060
MTProto#1003:Reschedule messages because bad_server_salt #6107397397028012064
MTProto#1003#Scheduller:Resending as new #9
MTProto#1003#Scheduller:Resending as new #10
MTProto#1003#Scheduller:Resending as new #12
MTProto#1002#Scheduller:Resending as new #5
MTProto#1002#Scheduller:Resending as new #6
MTProto#1002#Scheduller:Resending as new #8
MTProto#1002#Scheduller:Resending as new #11
ActorDispatcher:Dispatching action: schedule for scheduller
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 12
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 20
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 32
MTProto#1003#Scheduller:Iteration: count: 3, confirm:0
MTProto#1003#Scheduller:Building package
ActorDispatcher:Dispatching action: schedule for scheduller
MTProto#1003#Scheduller:Adding package: #9 ping#7abe77ec (6107397397028012068, 7)
MTProto#1003#Scheduller:Adding package: #10 get_future_salts#b921bd04 (6107397397028012072, 9)
Scheduller:Prepare package: account.registerDevice#446c712c of size 84
Scheduller:Total size: 84
Scheduller:Prepare package: ping_delay_disconnect#f3427b8c of size 16
Scheduller:Total size: 100
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 108
Scheduller:Prepare package: ping#7abe77ec of size 12
Scheduller:Total size: 120
MTProto#1002#Scheduller:Iteration: count: 4, confirm:0
MTProto#1002#Scheduller:Building package
MTProto#1003#Scheduller:Adding package: #12 ping#7abe77ec (6107397397028012076, 11)
MTProto#1002#Scheduller:Adding package: #5 account.registerDevice#446c712c (6107397397028012080, 9)
MTProto#1003#Scheduller:Sending Package (6107397397028012084, 12)
MTProto#1002#Scheduller:Adding package: #6 ping_delay_disconnect#f3427b8c (6107397397028012088, 11)
MTProto#1002#Scheduller:Adding package: #8 get_future_salts#b921bd04 (6107397397028012092, 13)
MTProto#1002#Scheduller:Adding package: #11 ping#7abe77ec (6107397397028012096, 15)
MTProto#1002#Scheduller:Sending Package (6107397397028012100, 16)
ActorDispatcher:Dispatching action: requestSalts for internal_actions
MTProto#1002:Salt check timeout
MTProto#1002:Too few actual salts: 0, requesting news
ActorDispatcher:Dispatching action: schedule for scheduller
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 8
MTProto#1002#Scheduller:Iteration: count: 1, confirm:0
MTProto#1002#Scheduller:Building package
MTProto#1002#Scheduller:Single package: #13 get_future_salts#b921bd04 (6107397397028012104, 17)
ActorDispatcher:Dispatching action: requestSalts for internal_actions
MTProto#1003:Salt check timeout
MTProto#1003:Too few actual salts: 0, requesting news
ActorDispatcher:Dispatching action: schedule for scheduller
Scheduller:Prepare package: get_future_salts#b921bd04 of size 8
Scheduller:Total size: 8
MTProto#1003#Scheduller:Iteration: count: 1, confirm:0
MTProto#1003#Scheduller:Building package
MTProto#1003#Scheduller:Single package: #14 get_future_salts#b921bd04 (6107397397028012108, 13)
ActorDispatcher:Dispatching action: requestSalts for internal_actions
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: requestSalts for internal_actions
ActorDispatcher:Dispatching action: schedule for scheduller
MTProto#1003#Transport3:Start reading message: pre
MTProto#1003#Transport3:Start reading message: 152
ActorDispatcher:Dispatching action: new for response
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002#Transport2:Start reading message: 184
MTProto#1003#Transport3:Start reading message: pre
MTProto#1003#Transport3:Start reading message: 1112
MTProto#1003:MTProtoMessage: new_session_created#9ec20908
TelegramApi#1001:mtproto#1003: onSessionCreated
ActorDispatcher:Dispatching action: new for response
MTProto#1003:MTProtoMessage: pong#347773c5
MTProto#1003:pong: -9163812034172340189
MTProto#1003#Scheduller:Forgetting message: #9
ActorDispatcher:Dispatching action: new for response
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: new_session_created#9ec20908
TelegramApi#1001:mtproto#1002: onSessionCreated
MTProto#1003#Transport3:Start reading message: pre
MTProto#1003:MTProtoMessage: future_salts#ae500895
MTProto#1003#Scheduller:Forgetting message: #10
MTProto#1003#Transport3:Start reading message: 88
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: pong#347773c5
MTProto#1002:pong: 2614958016563426611
MTProto#1002#Scheduller:Forgetting message: #6
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: msgs_ack#62d6b459
MTProto#1002:msgs_ack: 6107397397028012080
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002#Transport2:Start reading message: 1112
ActorDispatcher:Dispatching action: new for response
MTProto#1003:MTProtoMessage: pong#347773c5
MTProto#1003:pong: -9041944040346766858
MTProto#1003#Scheduller:Forgetting message: #12
MTProto#1003#Transport3:Start reading message: pre
MTProto#1003#Transport3:Start reading message: 1112
ActorDispatcher:Dispatching action: new for response
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: future_salts#ae500895
MTProto#1003:MTProtoMessage: future_salts#ae500895
MTProto#1003#Scheduller:Forgetting message: #14
MTProto#1002#Scheduller:Forgetting message: #8
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002#Transport2:Start reading message: 88
ActorDispatcher:Dispatching action: new for response
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002:MTProtoMessage: pong#347773c5
MTProto#1002:pong: 8255254634638895934
MTProto#1002#Scheduller:Forgetting message: #11
MTProto#1002#Transport2:Start reading message: 1112
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: future_salts#ae500895
MTProto#1002#Scheduller:Forgetting message: #13
MTProto#1002#Transport2:Start reading message: pre
MTProto#1002#Transport2:Start reading message: 104
ActorDispatcher:Dispatching action: new for response
MTProto#1002:MTProtoMessage: rpc_result#f35c6d01
MTProto#1002:rpc_result: 6107397397028012080
MTProto#1002:Auth key invalidated
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: checkDestroy for connector
TransportTcpPool#1001:Destroying contexts
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: checkDestroy for connector
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
TelegramApi#1001:Timeout Iteration
Exception in thread "main" TelegramApi#1001:RPC #0: Timeout (500010 ms)
TelegramApi#1001:Timeout Iteration
org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:309)
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:400)
    at com.wonderbiz.wtchat.Application.login(Application.java:397)
    at com.wonderbiz.wtchat.Application.main(Application.java:60)
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller

TelegramApi#1001:Timeout Iteration
Exception in thread "main" TelegramApi#1001:RPC #0: Timeout (500010 ms)
TelegramApi#1001:Timeout Iteration
org.telegram.api.engine.TimeoutException
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:309)
    at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:400)
    at com.wonderbiz.wtchat.Application.login(Application.java:397)
    at com.wonderbiz.wtchat.Application.main(Application.java:60)
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller
ActorDispatcher:Dispatching action: schedule for scheduller

**Comment by vaibhavthapliyal** [comment]
Hi,
It seems that it was an issue with the production ip-address.

Using this ip as the production ip works for me: "149.154.171.5".

You can try the following ip-addresses from here if this doesn't work for you:https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/config.h#L221
